 controller_list:
  - name: joint_position_example_controller
    action_ns: joint_position_example_controller
    type: franka_example_controllers/JointpositionExampleController
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: franka_gripper
    action_ns: gripper_action
    type: franka_gazebo/FrankaGripperSim
    default: true
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
